#!/bin/sh
# business-muumuu

## Require the administrator password
sudo -v

## Keep updating `sudo` timestamp until `business-muumuu` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

## Exit on any failure
set -e

./business

./muumuu

echo "Pre-existing dotfiles in $USER's home directory have been replaced – for changes to take effect, reload shell"
echo "NOTE: If your Git username and email address were configured locally prior to running this installer, you will need to set them again"
