#!/bin/sh
# business

## Use setup helpers for the BusinessMuumuu configuration stage
source support/setup-helpers

## Require the administrator password
sudo -v

## Keep updating `sudo` timestamp until `business` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

## Configuration stage files to be run
business_files=(
  cli
  package-managers
  code
  settings
  shells
  fonts
)

## Run configuration stage files
sourceinator business_files[@] "configure/"
