#!/usr/bin/env bash
# filezilla

####= SuitAndCape FileZilla (Mac) Settings
##============================================================================##

echo "Adjusting FileZilla settings"



## Kill FileZilla
appkillinator "FileZilla"
