#!/usr/bin/env bash
# firefoxdeveloperedition

####= SuitAndCape FirefoxDeveloperEdition (Mac) Settings
##============================================================================##

echo "Adjusting FirefoxDeveloperEdition settings"

## Expand FirefoxDeveloperEdition's print dialog box by default
defaults write org.mozilla.firefoxdeveloperedition PMPrintingExpandedStateForPrint2 -bool true

## Kill FirefoxDeveloperEdition
appkillinator "FirefoxDeveloperEdition"
