#!/usr/bin/env bash
# firefox

####= SuitAndCape Firefox (Mac) Settings
##============================================================================##

echo "Adjusting Firefox settings"

## Expand Firefox's print dialog box by default
defaults write org.mozilla.firefox PMPrintingExpandedStateForPrint2 -bool true

## Kill Firefox
appkillinator "Firefox"
