#!/usr/bin/env bash
# opera

####= SuitAndCape Opera (Mac) Settings
##============================================================================##

echo "Adjusting Opera settings"

## Do not automatically send Opera crash reports to Opera
defaults write com.operasoftware.Opera OPEnableCrashLogsUpload -bool false

## Expand Opera's print dialog box by default
defaults write com.operasoftware.Opera PMPrintingExpandedStateForPrint2 -bool true

## Kill Opera
appkillinator "Opera"
