#!/usr/bin/env bash
# osx-settings

####= SuitAndCape OS X System Settings
##============================================================================##

## Require the administrator password
sudo -v

## Keep updating `sudo` timestamp until `osx-settings` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

##== General and Miscellany ===================================================#

echo "Beginning OS X setup"

## Menu-select style computer naming process
echo -e "Would you like to name this computer?"
echo -e "\tName the computer [Y/y]"
echo -e "\tDo not name the computer [N/n]"
while true; do
  read -r user_answer
  case $user_answer in
    Y|y)
      echo "Enter the computer's name:"
      read -r new_computer_name
      ## Set new computer name
      sudo scutil --set ComputerName "${new_computer_name}"
      ## Set new host name
      sudo scutil --set HostName "${new_computer_name}"
      ## Set new local host name
      sudo scutil --set LocalHostName "${new_computer_name}"
      ## Set new NetBIOS name
      sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "${new_computer_name}"
      echo "The computer's name: \"${new_computer_name}\""
      echo "The computer's host name: \"${new_computer_name}\"" ; break ;;
    N|n)
      echo "The computer's name has not been altered" ; break ;;
    *)
      echo "Invalid option, please try again" ;;
  esac
done

## Enable access to the MacBook SuperDrive
sudo nvram boot-args="mbasd=1"

## Set appearance color (buttons, menus, and windows) to Blue/default
## (alternative: 6=Graphite)
defaults write NSGlobalDomain AppleAquaColorVariant -int 1

## Highlight color values:
  ## "1.000000 0.733333 0.721569": Red
  ## "1.000000 0.874510 0.701961": Orange
  ## "1.000000 0.937255 0.690196": Yellow
  ## "0.752941 0.964706 0.678431": Green
  ## "0.968627 0.831373 1.000000": Purple
  ## "1.000000 0.749020 0.823529": Pink
  ## "0.929412 0.870588 0.792157": Brown
  ## "0.847059 0.847059 0.862745": Graphite
  ## "0.129842 0.129846 0.129844": Lead (custom)
  ## "0.260517 0.260524 0.260521": Tungsten (custom)
  ## "0.837418 0.837438 0.837427": Silver (custom)
  ## "0.921431 0.921453 0.921441": Mercury (custom)

## Highlight color => ...
  ## Pink
defaults write NSGlobalDomain AppleHighlightColor -string "1.000000 0.749020 0.823529"
  ## Blue/default
# defaults delete NSGlobalDomain AppleHighlightColor

## Click in the scroll bar to Jump to the Spot That's Clicked
## (alternative: 0=Jump to the Next Page)
defaults write NSGlobalDomain AppleScrollerPagingBehavior -int 1

## Always show the scroll bar
## (alternatives: "Automatic"|"WhenScrolling")
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

## Disable opening and closing window animations
# defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool false

## Ask to keep changes when closing unsaved documents
defaults write NSGlobalDomain NSCloseAlwaysConfirmsChanges -bool true

## Disable automatic termination of applications that have been "inactive"
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

## Disable save to iCloud by default/enable save to disk by default
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

## Expand the save display panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

## Set the recent places dropdown limit to thirty five destinations
defaults write NSGlobalDomain NSNavRecentPlacesLimit -int 35

## Display caret notation style ASCII control characters in standard text views
defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true

## Do not use the focus ring animation
# defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

## Set Cocoa application windows resize speed to Mega-Fast
defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

## Expand the print display panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

## Disable the crash reporter dialog box
## (alternative: crashreport)
# defaults write com.apple.CrashReporter DialogType none

## Disable the "Are you sure..." opening application warning dialog box
defaults write com.apple.LaunchServices LSQuarantine -bool false

## Enable AirDrop over Ethernet and on unsupported Macs
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

## Check for software updates Once a day, instead of weekly
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

## Enable HelpViewer DevMode/stop help windows from overlaying other screens
defaults write com.apple.helpviewer DevMode -bool true

## Quit the printer application automatically when all print jobs are finished
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

## Disable saving state after closing an application/system-wide window resume
# defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

## Remove duplicates from the "Open With" menu
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

##== Accessibility ============================================================#

echo "Adjusting accessibility settings"

## Shake mouse pointer to locate is...
  ## Enabled
# defaults write "${HOME}"/Library/Preferences/.GlobalPreferences CGDisableCursorLocationMagnification -bool false
  ## Disabled
defaults write "${HOME}"/Library/Preferences/.GlobalPreferences CGDisableCursorLocationMagnification -bool true

## Enable Dictation
# defaults write com.apple.assistant.support "Assistant Enabled" -bool true
# defaults write com.apple.assistant.support "Dictation Enabled" -bool true
# defaults write com.apple.speech.recognition.AppleSpeechRecognition.prefs DictationIMMasterDictationEnabled -bool true

## Play video descriptions when available
# defaults write com.apple.mediaaccessibility MAAudibleMediaPrefPreferDescriptiveVideo -bool true

## Style for subtitles and captions values:
  ## "MACaptionProfile-Default":   Default
  ## "MACaptionProfile-Classic":   Classic
  ## "MACaptionProfile-LargeText": Large Text

## Style for subtitles and captions => Large Text
defaults write com.apple.mediaaccessibility MACaptionActiveProfile -string "MACaptionProfile-LargeText"

## Enable offline Dictation use and continuous Dictation with live feedback
# defaults write com.apple.speech.recognition.AppleSpeechRecognition.prefs DictationIMUseOnlyOfflineDictation -bool true

## Speak selected text when the key is pressed/enable Text to Speech
# defaults write com.apple.speech.synthesis.general.prefs SpokenUIUseSpeakingHotKeyFlag -bool true

## Announce when alerts are displayed
# defaults write com.apple.speech.synthesis.general.prefs TalkingAlertsSpeakTextFlag -bool true

## Enable time announcement
# defaults write com.apple.speech.synthesis.general.prefs TimeAnnouncementPrefs -dict-add "TimeAnnouncementsEnabled" -bool true

## Time announcement interval values:
  ## "EveryHalfHourInterval":    On the half hour
  ## "EveryHourInterval":        On the hour
  ## "EveryQuarterHourInterval": On the quarter hour

## Announce the time => On the hour
# defaults write com.apple.speech.synthesis.general.prefs TimeAnnouncementPrefs -dict-add "TimeAnnouncementsIntervalIdentifier" -string "EveryHourInterval"

## Set zoom cursor style to Crosshair
## (alternative: 1=System Cursor)
defaults write com.apple.universalaccess closeViewCursorType -int 2

## Use keyboard shortcuts to zoom
# defaults write com.apple.universalaccess closeViewHotkeysEnabled -bool true

## Set initial press-on-release-off zoom size to...
  ## Normal
# defaults write com.apple.universalaccess closeViewPoroZoomFactor -float 3.4241089820861816
  ## 1.5x
defaults write com.apple.universalaccess closeViewPoroZoomFactor -float 5.13616347312927240
  ## 2x
# defaults write com.apple.universalaccess closeViewPoroZoomFactor -float 6.8482179641723632

## Enable press-on-release-off zoom by holding `[⌃]+[⌥]`
# defaults write com.apple.universalaccess closeViewPressOnReleaseOff -bool true

## Zoom using the scroll gesture/wheel with the `[⌃]` modifier key
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144

## Enable smooth images when zoomed
defaults write com.apple.universalaccess closeViewSmoothImages -bool true

## Enable zoom's ability to follow the `[⇥]` keyboard focus
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

## Picture-in-Picture zoom style
## (alternative: 0=Fullscreen)
defaults write com.apple.universalaccess closeViewZoomMode -int 1

## Set the display contrast strength to Medium
## (range: 0=Normal–1=Maximum)
# defaults write com.apple.universalaccess contrast -float 0.5

## Differentiate without color
# defaults write com.apple.universalaccess differentiateWithoutColor -bool true

## Flash the screen when an alert sound occurs
# defaults write com.apple.universalaccess flashScreen -bool true
# defaults write com.apple.systemsound com.apple.sound.beep.flash -int 1

## Use grayscale
# defaults write com.apple.universalaccess grayscale -bool true

## Increase contrast
# defaults write com.apple.universalaccess increaseContrast -bool true

## Set the cursor size to Semi-Large
## (range: 1=Normal–4=Large)
# defaults write com.apple.universalaccess mouseDriverCursorSize -float 2.8

## Reduce transparency
# defaults write com.apple.universalaccess reduceTransparency -bool true

## Play stereo audio as mono
# defaults write com.apple.universalaccess stereoAsMono -bool true

## Enable VoiceOver
# defaults write com.apple.universalaccess voiceOverOnOffKey -bool true

## Invert colors
# defaults write com.apple.universalaccess whiteOnBlack -bool true
# defaults write com.apple.CoreGraphics DisplayUseInvertedPolarity -bool true

##== Activity Monitor =========================================================#

echo "Adjusting Activity Monitor settings"

## Activity Monitor's Dock icon visual values:
  ## 0: Show Application Icon
  ## 2: Show Network Usage
  ## 3: Show Disk Activity
  ## 5: Show CPU Usage
  ## 6: Show CPU History

## Visualization of Activity Monitor's Dock icon => Show CPU Usage
defaults write com.apple.ActivityMonitor IconType -int 5

## Set the graph type to Data in the Activity Monitor's Disk tab
## (alternative: 0=IO)
defaults write com.apple.ActivityMonitor DiskGraphType -int 1

## Set the graph type to Data in the Activity Monitor's Network tab
## (alternative: 0=Packets)
defaults write com.apple.ActivityMonitor NetworkGraphType -int 1

## Open the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

## View Activity Monitor processes values:
  ## 0:   Applications in last 8 hours
  ## 100: All Processes
  ## 101: All Processes, Hierarchically
  ## 102: My Processes
  ## 103: System Processes
  ## 104: Other User Processes
  ## 105: Active Processes
  ## 106: Inactive Processes
  ## 107: Windowed Processes

## View Activity Monitor processes => All Processes
defaults write com.apple.ActivityMonitor ShowCategory -int 100

## Sort results by CPU usage in Activity Monitor
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0

## Activity Monitor update frequency values:
  ## 1: Very often (1 sec)
  ## 2: Often (2 sec)
  ## 5: Normally (5 sec)

## Activity Monitor update frequency => Often (2 sec)
defaults write com.apple.ActivityMonitor UpdatePeriod -int 2

##== Audio and Sound ==========================================================#

echo "Adjusting audio/sound settings"

## Startup sound effects are...
  ## Enabled
# sudo nvram -d SystemAudioVolume
  ## Disabled
sudo nvram SystemAudioVolume=" "

## Do not play feedback when volume is changed
defaults write NSGlobalDomain com.apple.sound.beep.feedback -bool false

## Increase Bluetooth headphone and headset sound quality
defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

## System Alert sound values:
  ## "/System/Library/Sounds/Basso.aiff":     Basso
  ## "/System/Library/Sounds/Blow.aiff":      Blow
  ## "/System/Library/Sounds/Bottle.aiff":    Bottle
  ## "/System/Library/Sounds/Frog.aiff":      Frog
  ## "/System/Library/Sounds/Funk.aiff":      Funk
  ## "/System/Library/Sounds/Glass.aiff":     Glass
  ## "/System/Library/Sounds/Hero.aiff":      Hero
  ## "/System/Library/Sounds/Morse.aiff":     Morse
  ## "/System/Library/Sounds/Ping.aiff":      Ping
  ## "/System/Library/Sounds/Pop.aiff":       Pop
  ## "/System/Library/Sounds/Purr.aiff":      Purr
  ## "/System/Library/Sounds/Sosumi.aiff":    Sosumi
  ## "/System/Library/Sounds/Submarine.aiff": Submarine
  ## "/System/Library/Sounds/Tink.aiff":      Tink

## System Alert sound => Submarine
defaults write com.apple.systemsound com.apple.sound.beep.sound -string "/System/Library/Sounds/Submarine.aiff"

## Play user interface sound effects
defaults write com.apple.systemsound com.apple.sound.uiaudio.enabled -bool true

##== Command Line Tools =======================================================#

echo "Adjusting command line tools/Xcode settings"

## Trim trailing whitespace in Xcode
defaults write com.apple.dt.Xcode DVTTextEditorTrimTrailingWhitespace -bool true

## Trim whitespace only lines in Xcode
# defaults write com.apple.dt.Xcode DVTTextEditorTrimWhitespaceOnlyLines -bool true

## Disable tabs (enable spaces) for indentation in Xcode
defaults write com.apple.dt.Xcode DVTTextIndentUsingTabs -bool false

## Show line numbers in Xcode
defaults write com.apple.dt.Xcode DVTTextShowLineNumbers -bool true

## Enable Xcode ruler and set ruler to column 80
defaults write com.apple.dt.Xcode DVTTextShowPageGuide -bool true
defaults write com.apple.dt.Xcode DVTTextPageGuideLocation -int 80

## Disable source control in Xcode
# defaults write com.apple.dt.Xcode IDESourceControlEnableSourceControl_7_1 -bool false

## Show toolbar build operation durations in Xcode
defaults write com.apple.dt.Xcode ShowBuildOperationDuration -bool true

##== Contacts/Address Book ====================================================#

echo "Adjusting Contacts/Address Book settings"

## Show contact first names Before last names in Contacts
## (alternative: 2=Following)
defaults write NSGlobalDomain NSPersonNameDefaultDisplayNameOrder -int 1

## Contacts short name format values:
  ## false, 0: Full Name
  ## true, 1:  First Name & Last Initial
  ## true, 2:  First Initial & Last Name
  ## true, 3:  First Name Only
  ## true, 4:  Last Name Only

## Contacts short name format => First Initial & Last Name
defaults write NSGlobalDomain NSPersonNameDefaultShortNameEnabled -bool true
defaults write NSGlobalDomain NSPersonNameDefaultShortNameFormat -int 2
defaults write com.apple.AddressBook ABShortNameStyle -int 2

## Prefer nicknames in Contacts
defaults write NSGlobalDomain NSPersonNameDefaultShouldPreferNicknamesPreference -bool true

## Show birthdays on the contact template in Contacts
defaults write com.apple.AddressBook ABBirthDayVisible -bool true

## Sort contacts by last name in Contacts
defaults write com.apple.AddressBook ABNameSortingFormat -string "sortingLastName sortingFirstName"

## Enable the Contacts debug menu
defaults write com.apple.AddressBook ABShowDebugMenu -bool true

##== Dashboard and Mission Control ============================================#

echo "Adjusting Dashboard and Mission Control settings"

## When switching to an application, switch to Space of the active application
defaults write NSGlobalDomain AppleSpacesSwitchOnActivate -bool true

## Enable Dashboard developer mode, allowing widgets to be kept on the desktop
defaults write com.apple.dashboard devmode -bool true

## Disable Dashboard
# defaults write com.apple.dashboard mcx-disabled -bool true

## Set the Mission Control animation speed to Mega-Fast
defaults write com.apple.dock expose-animation-duration -float 0.001

## Group Mission Control windows in Classic Exposé format, instead of by app
defaults write com.apple.dock expose-group-by-app -bool false

## Do not automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

## Show the Dashboard as an Overlay, instead of a Space
defaults write com.apple.dock dashboard-in-overlay -bool true

##== Datetime and Locale ======================================================#

echo "Adjusting date, time, and locale settings"

## Set the timezone
## (alternatives: enter `sudo systemsetup -settimezone`)
# sudo systemsetup -settimezone "America/Los_Angeles" > /dev/null

## Set preferred time format to...
  ## 12-hour time
# defaults write NSGlobalDomain AppleICUForce12HourTime -bool true
  ## 24-hour time
defaults write NSGlobalDomain AppleICUForce24HourTime -bool true

## Set languages in order of preference
defaults write NSGlobalDomain AppleLanguages -array "en"

## Set preferred currency to USD
defaults write NSGlobalDomain AppleLocale -string "en_US@currency=USD"

## Set preferred units of measurement to Inches
## (alternative: "Centimeters")
defaults write NSGlobalDomain AppleMeasurementUnits -string "Inches"

## Enable metric units
defaults write NSGlobalDomain AppleMetricUnits -bool true

##== Desktop and Finder =======================================================#

echo "Adjusting desktop and Finder settings"

## Show all filename extensions in Finder
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

## Set Finder sidebar icon size to Medium
## (range: 1=Small–3=Large)
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

## Set the Quick Look windows open and close speed to Mega-Fast
defaults write NSGlobalDomain QLPanelAnimationDuration -int 0

## Enable spring-loading for directories
defaults write NSGlobalDomain com.apple.springing.enabled -bool true

## Remove the spring-loading directory delay
defaults write NSGlobalDomain com.apple.springing.delay -int 0

## Do not allow .DS_Store files to be created on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

## Reveal all hidden files
defaults write com.apple.finder AppleShowAllFiles -bool true

## Disable all window and Get Info animations
# defaults write com.apple.finder DisableAllAnimations -bool true

## When performing a search, search Current Folder by default
## (alternatives: "SCev"=This Mac|"SCsp"=Previous Scope)
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

## Disable the "Are you sure..." extension change warning dialog box
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

## Expand all Get Info panes by default, except for "Preview"
defaults write com.apple.finder FXInfoPanesExpanded -dict \
  Comments -bool true \
  General -bool true \
  MetaData -bool true \
  Name -bool true \
  OpenWith -bool true \
  Preview -bool false \
  Privileges -bool true

## Arrange Finder file values:
  ## "Application"
  ## "Date Added"
  ## "Date Created"
  ## "Date Last Opened"
  ## "Date Modified"
  ## "Kind"
  ## "Name"
  ## "None"
  ## "Size"
  ## "Tags"

## Arrange Finder files => Name
defaults write com.apple.finder FXPreferredGroupBy -string "Name"

## Set the default Finder view style to Column View
## (alternatives: "Flwv"=Cover Flow|"Nlsv"=List View|"icnv"=Icon View)
defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

## Finder target window location values:
  ## "PfAF", "file:///System/Library/CoreServices/Finder.app/Contents/Resources/MyLibraries/myDocuments.cannedSearch"
    ##: All My Files
  ## "PfCm", ""
    ##: Computer
  ## "PfDe", "file://${HOME}/Desktop/"
    ##: Desktop
  ## "PfDo", "file://${HOME}/Documents/"
    ##: Documents
  ## "PfHm", "file://${HOME}/"
    ##: User's Home directory
  ## "PfID", "file://${HOME}/Library/Mobile%20Documents/com~apple~CloudDocs/"
    ##: iCloud Drive
  ## "PfLo", "file://PATH/TO/LOCATION/"
    ##: Custom/Other...
  ## "PfVo", "file:///"
    ##: Volume

## New Finder target window location => User's Home directory
defaults write com.apple.finder NewWindowTarget -string "PfHm"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"

## Enable text selection in Quick Look windows
defaults write com.apple.finder QLEnableTextSelection -bool true

## Enable `[⌘]+[Q]` to force quit Finder and hide desktop icons
defaults write com.apple.finder QuitMenuItem -bool true

## Show icons for external hard drives on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true

## Show icons for hard drives on the desktop
# defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true

## Show icons for servers on the desktop
# defaults write com.apple.finder ShowMountedServersOnDesktop -bool true

## Show path bar in Finder
# defaults write com.apple.finder ShowPathbar -bool true

## Show icons for removable media on the desktop
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

## Show status bar in Finder
defaults write com.apple.finder ShowStatusBar -bool true

## Show the full POSIX path in the Finder window title bar
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

## Open a new Finder window automatically when a volume is mounted
# defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
# defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
# defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

## Disable disk image checksum verification, only images from trusted sources
defaults write com.apple.frameworks.diskimages skip-verify -bool true
defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

## Sort by values:
  ## "dateAdded":      Date Added
  ## "dateCreated":    Date Created
  ## "dateLastOpened": Date Last Opened
  ## "dateModified":   Date Modified
  ## "grid":           Snap to Grid
  ## "kind":           Kind
  ## "label":          Tags
  ## "name":           Name
  ## "none":           None
  ## "size":           Size

## Sort icons in the desktop and Finder's icon view => Snap to Grid
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" "${HOME}"/Library/Preferences/com.apple.finder.plist

## Set the grid spacing to Semi-Large in the desktop and Finder's icon view
## (range: 1=Small–100=Large)
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 90" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 90" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 90" "${HOME}"/Library/Preferences/com.apple.finder.plist

## Set the icon size to Medium in the desktop and Finder's icon view
## (range: 16=Small–128=Large)
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:iconSize 64" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 64" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:iconSize 64" "${HOME}"/Library/Preferences/com.apple.finder.plist

## Display icon info on the Bottom in the desktop and Finder's icon view
## (alternative: false=Right Side)
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:labelOnBottom true" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:labelOnBottom true" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:labelOnBottom true" "${HOME}"/Library/Preferences/com.apple.finder.plist

## Show icon previews in the desktop and Finder's icon view
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:showIconPreview true" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:showIconPreview true" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:showIconPreview true" "${HOME}"/Library/Preferences/com.apple.finder.plist

## Show item info for icons in the desktop and Finder's icon view
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" "${HOME}"/Library/Preferences/com.apple.finder.plist

## Set the text size to Medium in the desktop and Finder's icon view
## (range: 10=Small–16=Large)
$PLISTBUDDY -c "Set :DesktopViewSettings:IconViewSettings:textSize 14" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :FK_StandardViewSettings:IconViewSettings:textSize 14" "${HOME}"/Library/Preferences/com.apple.finder.plist
$PLISTBUDDY -c "Set :StandardViewSettings:IconViewSettings:textSize 14" "${HOME}"/Library/Preferences/com.apple.finder.plist

## Sort Finder file values:
  ## "ascd": Date Created
  ## "dnam": Name
  ## "kipl": Kind
  ## "labl": Tags
  ## "logs": Size
  ## "ludt": Date Last Opened
  ## "modd": Date Modified
  ## "pAdd": Date Added

## Sort Finder files in column view => Kind
$PLISTBUDDY -c "Set :StandardViewOptions:ColumnViewOptions:ArrangeBy kipl" "${HOME}"/Library/Preferences/com.apple.finder.plist

## Set the Finder file font size to Large in column view
## (range: 10=Small–16=Large)
$PLISTBUDDY -c "Set :StandardViewOptions:ColumnViewOptions:FontSize 16" "${HOME}"/Library/Preferences/com.apple.finder.plist

## Show Finder file preview in column view
$PLISTBUDDY -c "Set :StandardViewOptions:ColumnViewOptions:ShowPreview true" "${HOME}"/Library/Preferences/com.apple.finder.plist

##== Disk Utility =============================================================#

echo "Adjusting Disk Utility settings"

## Enable the Disk Utility debug menu
defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true

## Show hidden routines for verifying image checksums in Disk Utility
defaults write com.apple.DiskUtility advanced-image-options -bool true

##== Display ==================================================================#

echo "Adjusting display/view settings"

## Enable automatic display brightness adjustment
# sudo defaults write /Library/Preferences/com.apple.iokit.AmbientLightSensor.plist "Automatic Display Enabled" -bool true

## Enable Retina resolutions (HiDPI display modes)
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

## Set font smoothing and anti-aliasing strength to Medium, for non-Apple LCDs
## (range: 0=Off–4=Strong)
defaults write NSGlobalDomain AppleFontSmoothing -int 2

## Show mirroring options in the menu bar when available
defaults write com.apple.airplay showInMenuBarIfPresent -bool true

##== Dock and Menu Bar ========================================================#

echo "Adjusting Dock and menu bar settings"

## Double-click a window's title bar to Maximize (zoom) the window
## (alternatives: "Mimimize"|"None")
defaults write NSGlobalDomain AppleActionOnDoubleClick -string "Maximize"

## Enable menu bar transparency
defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool true

## For the Dock and menu bar, use the...
  ## Dark setting
# defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"
  ## Light/default setting
# defaults delete NSGlobalDomain AppleInterfaceStyle

## Automatically hide and show the dock
# defaults write com.apple.dock autohide -bool true

## Remove the Dock's auto-hiding delay
defaults write com.apple.dock autohide-delay -int 0

## Set the Dock's auto-hiding animations speed to Mega-Fast
defaults write com.apple.dock autohide-time-modifier -int 0

## Add Launchpad to the Dock
defaults write com.apple.dock checked-for-launchpad -bool true

## Lock the contents of the Dock
# defaults write com.apple.dock contents-immutable -bool true

## Enable spring-loading for items on the Dock
defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

## Set the Dock icon magnification strength to Medium
## (range: 16=Minimum–128=Maximum)
defaults write com.apple.dock largesize -int 64

## Disable Dock application opening animations
# defaults write com.apple.dock launchanim -bool false

## Enable Dock magnification
defaults write com.apple.dock magnification -bool true

## Minimize Dock items using the Genie effect
## (alternatives: "scale"|"suck")
defaults write com.apple.dock mineffect -string "genie"

## Do not minimize windows into Dock application icon
defaults write com.apple.dock minimize-to-application -bool false

## Enable highlighting in the grid view of Dock stacks
defaults write com.apple.dock mouse-over-hilite-stack -bool true

## Set the Dock's screen position to the Right
## (alternatives: "bottom"|"left")
defaults write com.apple.dock orientation -string "right"

## Pin the Dock to the Middle of the screen's edge
## (alternatives: "start"=Left Side|"end"=Right Side)
# defaults write com.apple.dock pinning -string "middle"

## Lock the position of the Dock
# defaults write com.apple.dock position-immutable -bool true

## Show indicator lights on Dock items for open applications
defaults write com.apple.dock show-process-indicators -bool true

## Enable transluscent Dock icons for hidden applications
defaults write com.apple.dock showhidden -bool true

## Lock the size of the Dock
# defaults write com.apple.dock size-immutable -bool true

## Only show open applications in the Dock
# defaults write com.apple.dock static-only -bool true

## Set the Dock icon size to Semi-Small
## (range: 16=Small–128=Large)
defaults write com.apple.dock tilesize -int 30

## Show battery percentage in the menu bar
defaults write com.apple.menuextra.battery ShowPercent -string "yes"

## Set preferred menu bar clock format to...
  ## Weekday Month Day Hour:Minute AM/PM (for 12-hour time)
# defaults write com.apple.menuextra.clock DateFormat -string "EEE MMM d h:mm a"
  ## Weekday Month Day Hour:Minute:Second (for 24-hour time)
defaults write com.apple.menuextra.clock DateFormat -string "EEE MMM d HH:mm:ss"

## Do not flash the time separators
defaults write com.apple.menuextra.clock FlashDateSeparators -bool false

## Disable analog/enable digital clock in the menu bar
defaults write com.apple.menuextra.clock IsAnalog -bool false

## Disable the Notification Center and remove its menu bar icon
# launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null

##== Font Book ================================================================#

echo "Adjusting Font Book settings"

## Enable automatic font activation in Font Book
## (alternative: "ATSAutoActivationDisable")
defaults write com.apple.ATS ATSAutoActivation -string "ATSAutoActivationEnable"

## Customize the Font Book sample text
defaults write com.apple.FontBook FBComparisonViewText -string "The quick brown fox jumps over the lazy dog."
defaults write com.apple.FontBook FBCustomSampleString -string "The quick brown fox jumps over the lazy dog."

## Set the Font Book default install loction to User
## (alternative: 1=Computer)
defaults write com.apple.FontBook FBDefaultInstallDomainRef -int 3

## Set Font Book preview type and preview mode to Repertoire
## (alternatives: 0=Custom|2=Sample|3=Show Font Info)
defaults write com.apple.FontBook FBPreviewTypeKey -int 1
defaults write com.apple.FontBook FBPreviewModeKey -int 1

## Resolve Font Book duplicates by moving files to the trash
defaults write com.apple.FontBook FBResolveByMovingToTrashKey -bool true

## Set the Font Book default sample font size to twenty four points
defaults write com.apple.FontBook FBSampleSize -int 24

##== Hot Corners ==============================================================#

echo "Adjusting Hot Corner settings"

## Hot Corner values:
  ## 0:  No option
  ## 2:  Mission Control
  ## 3:  Show application windows
  ## 4:  Desktop
  ## 5:  Start screen saver
  ## 6:  Disable screen saver
  ## 7:  Dashboard
  ## 10: Put display to sleep
  ## 11: Launchpad
  ## 12: Notification Center

## Top left of screen/Hot Corner => Mission Control
# defaults write com.apple.dock wvous-tl-corner -int 2
# defaults write com.apple.dock wvous-tl-modifier -int 0

## Top right of screen/Hot Corner => Dashboard
# defaults write com.apple.dock wvous-tr-corner -int 7
# defaults write com.apple.dock wvous-tr-modifier -int 0

## Bottom left of screen/Hot Corner => Put display to sleep
defaults write com.apple.dock wvous-bl-cxorner -int 10
defaults write com.apple.dock wvous-bl-modifier -int 0

## Bottom right of screen/Hot Corner => Start screen saver
defaults write com.apple.dock wvous-br-corner -int 5
defaults write com.apple.dock wvous-br-modifier -int 0

##== Images and Pictures ======================================================#

echo "Adjusting image/picture/photo settings"

## Create a directory for screenshots
mkdir -p "${SCREENSHOTS_DIR}"

## Save screen captures in the screenshots directory
defaults write com.apple.screencapture location -string "${SCREENSHOTS_DIR}"

## Do not automatically open Photos when devices are plugged in
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true

## Disable screenshot shadows
defaults write com.apple.screencapture disable-shadow -bool true

## Save screenshots as PNGs
## (alternatives: "bmp"|"gif"|"jpg"|"pdf"|"tiff")
defaults write com.apple.screencapture type -string "png"

##== Keyboard =================================================================#

echo "Adjusting keyboard settings"

## Enable automatic keyboard brightness adjustment in low light
# sudo defaults write /Library/Preferences/com.apple.iokit.AmbientLightSensor.plist "Automatic Keyboard Enabled" -bool true

## Set keyboard dimmer timer to one hundred eighty seconds (three minutes)
# sudo defaults write /Library/Preferences/com.apple.iokit.AmbientLightSensor.plist "Keyboard Dim Time" -int 180

## Allow All Controls full keyboard access
## (alternative: 1=Text Boxes and Lists)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

## Disable press-and-hold character accent menu access in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

## Set the initial key repeat delay to Mega-Fast (tweleve milliseconds)
## (range: 15=Fast–120=Long)
defaults write NSGlobalDomain InitialKeyRepeat -int 12

## Set the keyboard key repeat speed to Mega-Fast
## (range: 2=Fast–300000=Off)
defaults write NSGlobalDomain KeyRepeat -int 0

## Disable smart dashes
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

## Disable smart quotes
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

## Disable automatic spelling correction (auto-correct)
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

## Unlink iTunes from the keyboard media keys
# launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

##== Mac App Store ============================================================#

echo "Adjusting Mac App Store settings"

## Enable the Mac App Store Debug Menu
defaults write com.apple.appstore ShowDebugMenu -bool true

## Enable the Mac App Store WebKit Developer Tools
defaults write com.apple.appstore WebKitDeveloperExtras -bool true

##== Mail =====================================================================#

echo "Adjusting Mail settings"

## Copy `name@example.com`, instead of `First Last <name@example.com>` in Mail
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

## Disable inline attachments, instead of showing mail attachment icons
defaults write com.apple.mail DisableInlineAttachmentViewing -bool true

## Disable replying animations in Mail
defaults write com.apple.mail DisableReplyAnimations -bool true

## Disable sending animations in Mail
defaults write com.apple.mail DisableSendAnimations -bool true

## Display emails in threaded mode descending by date in Mail
defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "yes"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "yes"
defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "received-date"

## Enable the To/Cc label in the Mail message list
defaults write com.apple.mail EnableToCcInMessageList -bool true

## Set the font size to fourteen pixels in Mail
defaults write com.apple.mail NSFontSize -int 14

## Check for new Mail messages every ten minutes
defaults write com.apple.mail PollTime -int 10

## Display unread Mail emails in bold font
defaults write com.apple.mail ShouldShowUnreadMessagesInBold -bool true

## Disable automatic spelling correction (auto-correct) in Mail
defaults write com.apple.mail SpellCheckingBehavior -string "NoSpellCheckingEnabled"

##== Messages =================================================================#

echo "Adjusting Messages settings"

## Show buddy pictures in Messages conversations
defaults write com.apple.iChat ShowAllBuddyPictures -bool true

## Set Messages text size to Semi-Large
## (range: 1=Small–7=Large)
defaults write com.apple.iChat TextSize -int 6

## Disable notifications about unknown contacts in Messages
defaults write com.apple.messageshelper.AlertsController NotifyAboutKnockKnockKey -bool false

## Disable sound effects in Messages
defaults write com.apple.messageshelper.AlertsController PlaySoundsKey -bool false

## Disable notifications about the user's name being mentioned in Messages
defaults write com.apple.messageshelper.AlertsController SOAlertsAddressMeKey -bool false

## Do not automatically substitute plain text smileys with emojis in Messages
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticEmojiSubstitutionEnablediMessage" -bool false

## Disable smart dashes Messages
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticDashSubstitutionEnabled" -bool false

## Disable smart quotes Messages
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticQuoteSubstitutionEnabled" -bool false

## Disable automatic spelling correction (auto-correct) in Messages
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "automaticSpellingCorrectionEnabled" -bool false

## Enable continuous spell checking in Messages
defaults write com.apple.messageshelper.MessageController SOInputLineSettings -dict-add "continuousSpellCheckingEnabled" -bool true

##== Mouse and Trackpad =======================================================#

echo "Adjusting Mouse and Trackpad settings"

## Enable Trackpad "three fingers swipe between pages" (scroll left and right)
defaults write NSGlobalDomain AppleEnableSwipeNavigateWithScrolls -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.threeFingerHorizSwipeGesture -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerHorizSwipeGesture -int 1

## Set mouse double-click speed/threshold to Semi-Fast
## (range: 5=Slow–0.15=Fast)
defaults write NSGlobalDomain com.apple.mouse.doubleClickThreshold -float 0.5

## Set mouse tracking speed to Semi-Fast
## (range: 0=Slow–3=Fast)
defaults write NSGlobalDomain com.apple.mouse.scaling -float 2.5

## Set scroll wheel and scrolling speed to Semi-Fast
## (range: 0=Slow–1=Fast)
defaults write NSGlobalDomain com.apple.scrollwheel.scaling -float 0.3125

## Disable natural (inverted) scrolling for mouse and Trackpad
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

## Enable Trackpad Force Click and Haptic Feedback
defaults write NSGlobalDomain com.apple.trackpad.forceClick -bool true
defaults write com.apple.AppleMultitouchTrackpad ForceSuppressed -bool false
defaults write com.apple.AppleMultitouchTrackpad ActuateDetents -bool true

## Set Trackpad tracking speed to Semi-Fast
## (range: 0=Slow–3=Fast)
defaults write NSGlobalDomain com.apple.trackpad.scaling -float 2.5

## Disable Trackpad "pinch with thumb and three fingers" Launchpad gesture
# defaults write com.apple.dock showLaunchpadGestureEnabled -int 0

## Enable Trackpad "tap to click", not press, for this user and the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

## Enable Trackpad silent clicking
defaults write com.apple.AppleMultitouchTrackpad ActuationStrength -int 0

## Enable Light Trackpad Haptic Feedback
## (alternatives: 1=Medium|2=Firm)
defaults write com.apple.AppleMultitouchTrackpad FirstClickThreshold -int 0
defaults write com.apple.AppleMultitouchTrackpad SecondClickThreshold -int 0

## Enable the bottom right corner of Trackpad as right-click (secondary click)
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

## Enable Trackpad three finger drag
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool true

##== Power Management and Screen State ========================================#

echo "Adjusting power management and screen state settings"

## Do not enter hibernation automatically
sudo pmset -a hibernatemode 0

## Disable the sudden motion sensor, for Solid-State Drives (SSDs)
sudo pmset -a sms 0

## Set standby delay timer to thirty six thousand seconds (ten hours)
sudo pmset -a standbydelay 36000

## Set sleep timer to thirty minutes, when battery powered
sudo pmset -b sleep 30

## Set sleep timer to sixty minutes (one hour), when charger powered
sudo pmset -c sleep 60

## Replace the sleep image file with a zero-byte file that can't be overwritten
sudo rm /private/var/vm/sleepimage
sudo touch /private/var/vm/sleepimage
sudo chflags uchg /private/var/vm/sleepimage

## Do not enter sleep mode automatically when the display is off
sudo systemsetup -setcomputersleep Off > /dev/null

## Set automatic restart after computer freeze
sudo systemsetup -setrestartfreeze on

## Set screen saver timer to six hundred seconds (ten minutes)
defaults -currentHost write com.apple.screensaver idleTime -int 600

## Show clock while the screen saver is active
# defaults -currentHost write com.apple.screensaver showClock -int 1

##== Preview ==================================================================#

echo "Adjusting Preview settings"

## Hide Preview's sidebar by default
defaults write "${HOME}"/Library/Containers/com.apple.Preview/Data/Library/Preferences/com.apple.Preview PVPDFSuppressSidebarOnOpening -bool true

## Print page scaled to fit, instead of scaled to 100% by default in Preview
defaults write com.apple.Preview PVImagePrintingScaleMode -bool false

##== QuickTime Player =========================================================#

echo "Adjusting QuickTime Player settings"

## Enable multiple simultaneous recordings in QuickTime
defaults write com.apple.QuickTimePlayerX MGAllowMultipleSimultaneousRecordings -bool true

## Force rounded corners on the QuickTime window
defaults write com.apple.QuickTimePlayerX MGCinematicWindowDebugForceNoRoundedCorners -bool true

## Automatically play video upon opening in QuickTime
defaults write com.apple.QuickTimePlayerX MGPlayMovieOnOpen -bool true

## Record in Maximum quality in QuickTime
## (alternative: "MGCompressionPresetHighQuality")
defaults write com.apple.QuickTimePlayerX MGRecordingCompressionPresetIdentifier -string "MGCompressionPresetMaximumQuality"

## Show mouse clicks when screen recording in QuickTime
defaults write com.apple.QuickTimePlayerX MGScreenRecordingDocumentShowMouseClicksUserDefaultsKey -bool true

##== Safari ===================================================================#

echo "Adjusting Safari settings"

## Safari opens with values:
  ## false, false: A new window
  ## false, true:  A new private window
  ## true, false:  All windows from last session

## Safari opens with => All windows from last session
defaults write com.apple.Safari AlwaysRestoreSessionAtLaunch -bool true
defaults write com.apple.Safari OpenPrivateWindowWhenNotRestoringSessionAtLaunch -bool false

## Always show the tab bar in Safari
# defaults write com.apple.Safari AlwaysShowTabBar -bool true

## Do not let Safari automatically open "safe" files after downloading
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

## Cookies and website values:
  ## 0, 2, 2: Always block
  ## 1, 0, 0: Always allow
  ## 2, 1, 1: Allow from websites I visit
  ## 3, 1, 1: Allow from current website only

## Cookies and website data => Allow from websites I visit
defaults write com.apple.Safari BlockStoragePolicy -int 2
defaults write com.apple.Safari WebKitStorageBlockingPolicy -int 1
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2StorageBlockingPolicy -int 1

## Do not use snapshot thumbnail caching for History or Top Sites in Safari
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

## Download list removal values:
  ## 0: Manually
  ## 1: When Safari quits
  ## 2: Upon successful download
  ## 3: After one day

## Remove download list items => After one day
defaults write com.apple.Safari DownloadsClearingPolicy -int 3

## Set Safari's download location to the current user's Downloads/ directory
# defaults write com.apple.Safari DownloadsPath -string "${HOME}/Downloads"

## Enable extensions in Safari
defaults write com.apple.Safari ExtensionsEnabled -bool true

## Make Safari's search banner use "Contains", not "Starts With", by default
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

## History removal values:
  ## 1:      After one day
  ## 7:      After one week
  ## 14:     After two weeks
  ## 31:     After one month
  ## 365:    After one year
  ## 365000: Manually

## Remove history items => After one month
defaults write com.apple.Safari HistoryAgeInDaysLimit -int 31

## Set Safari's homepage to "about:blank"
defaults write com.apple.Safari HomePage -string "about:blank"

## Show the Develop menu in Safari's menu bar
defaults write com.apple.Safari IncludeDevelopMenu -bool true

## Enable the Safari internal debug menu
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

## New tabs and windows values:
  ## 0: Homepage
  ## 1: Empty Page
  ## 2: Same Page
  ## 4: Favorites/Top Sites
  ## 5: Tabs for... (tabs only)

## New tabs open with => Homepage
defaults write com.apple.Safari NewTabBehavior -int 0

## New windows open with => Homepage
defaults write com.apple.Safari NewWindowBehavior -int 0

## Preload Top Hit in the background in Safari's Smart Search Field
defaults write com.apple.Safari PreloadTopHit -bool true

## Remove Top Sites and Reading List icons from Safari's bookmarks bar
defaults write com.apple.Safari ProxiesInBookmarksBar "()"

## Website use of location services values:
  ## 0: Deny without prompting
  ## 1: Prompt for each website once each day
  ## 2: Prompt for each website one time only

## Website use of location services => Prompt for each website one time only
defaults write com.apple.Safari SafariGeolocationPermissionPolicy -int 2

## Search engine values:
  ## "com.bing.www":   Bing
  ## "com.duckduckgo": DuckDuckGo
  ## "com.google.www": Google
  ## "com.yahoo.www":  Yahoo

## Search engine => Google
# defaults write com.apple.Safari SearchProviderIdentifier -string "com.google.www"

## Ask websites not to track me in Safari
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true

## Show the favorites bar in Safari
defaults write com.apple.Safari ShowFavoritesBar -bool true
defaults write com.apple.Safari ShowFavoritesBar-v2 -bool true

## Show favorites in Safari's Smart Search Field
defaults write com.apple.Safari ShowFavoritesUnderSmartSearchField -bool true

## Show full website address in Safari's Smart Search Field
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

## Hide the sidebar in Safari's Top Sites
defaults write com.apple.Safari ShowSidebarInTopSites -bool false

## Supress search engine and Spotlight suggestions from querying through Apple
defaults write com.apple.Safari SuppressSearchSuggestions -bool true
defaults write com.apple.Safari UniversalSearchEnabled -bool false

## Always open pages in tabs instead of windows in Safari
## (alternatives: 0=Never|1=Automatically)
defaults write com.apple.Safari TabCreationPolicy -int 2

## Enable Web Inspector in Safari
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

## Use `[⇥]` to highlight/scroll through each element on a web page in Safari
defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true

## Enable Quick Website Search in Safari's Smart Search Field
defaults write com.apple.Safari WebsiteSpecificSearchEnabled -bool true

## Use `[⌫]` to go to the previous page in Safari history
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true

##== Security and Privacy =====================================================#

echo "Adjusting security/privacy settings"

## Allow signed software to receive incoming connections through the Firewall
sudo defaults write /Library/Preferences/com.apple.alf allowsignedenabled -bool true

## Turn on Application Layer Firewall, preventing unauthorized connections
sudo defaults write /Library/Preferences/com.apple.alf globalstate -bool true

## Enable Firewall logging
sudo defaults write /Library/Preferences/com.apple.alf loggingenabled -bool true

## Enable Firewall stealth mode
## NOTE: Stealth mode prevents your computer from responding to ICMP ping
#requests, and answering connection attempts from closed TCP or UDP ports
sudo defaults write /Library/Preferences/com.apple.alf stealthenabled -bool true

## Disable infrared receiver controller
sudo defaults write /Library/Preferences/com.apple.driver.AppleIRController DeviceEnabled -bool false

## Disable the secure virtual memory (encrypted swap)
# sudo defaults write /Library/Preferences/com.apple.virtualMemory DisableEncryptedSwap -bool true

## Allow applications to be downloaded from...
  ## Mac App Store and identified developers
sudo spctl --master-enable --label "Developer ID"
  ## Anywhere (disable Gatekeeper)
# sudo spctl --master-disable

## Login from sleep or screen saver values:
  ## false, 0:    No password required
  ## true, 0:     immediately
  ## true, 5:     5 seconds
  ## true, 60:    1 minute
  ## true, 300:   5 minutes
  ## true, 900:   15 minutes
  ## true, 3600:  1 hour
  ## true, 14400: 4 hours
  ## true, 28800: 8 hours

## Require password to login after sleep or screen saver => immediately
defaults write com.apple.screensaver askForPassword -bool true
defaults write com.apple.screensaver askForPasswordDelay -int 0

##== Spotlight ================================================================#

echo "Adjusting Spotlight settings"

## Disable Spotlight helper and menu bar icon
## (alternative: 755=Enable)
# sudo chmod 600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search

## Disable Spotlight indexing for mounted but not yet indexed volumes
sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array "/Volumes"

## Rearrange Spotlight indexing order and disable certain file types
## NOTE: Remove options beginning with "MENU_" when using OS X 10.9 or below
defaults write com.apple.spotlight orderedItems -array \
  '{"enabled" = 1;"name" = "APPLICATIONS";}' \
  '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
  '{"enabled" = 1;"name" = "DIRECTORIES";}' \
  '{"enabled" = 1;"name" = "PDF";}' \
  '{"enabled" = 1;"name" = "FONTS";}' \
  '{"enabled" = 1;"name" = "MENU_DEFINITION";}' \
  '{"enabled" = 1;"name" = "MENU_CONVERSION";}' \
  '{"enabled" = 0;"name" = "BOOKMARKS";}' \
  '{"enabled" = 0;"name" = "CONTACT";}' \
  '{"enabled" = 0;"name" = "DOCUMENTS";}' \
  '{"enabled" = 0;"name" = "EVENT_TODO";}' \
  '{"enabled" = 0;"name" = "IMAGES";}' \
  '{"enabled" = 0;"name" = "MESSAGES";}' \
  '{"enabled" = 0;"name" = "MOVIES";}' \
  '{"enabled" = 0;"name" = "MUSIC";}' \
  '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
  '{"enabled" = 0;"name" = "SOURCE";}' \
  '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
  '{"enabled" = 0;"name" = "MENU_EXPRESSION";}' \
  '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}' \
  '{"enabled" = 0;"name" = "MENU_OTHER";}' \
  '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'

## Restart metadata server, including the Spotlight client
killall mds > /dev/null 2>&1

## Set the indexing status for the provided volumes to on
sudo mdutil -i on / > /dev/null

## Erase and rebuild the local store for the volumes (the index)
sudo mdutil -E / > /dev/null

##== Terminal =================================================================#

echo "Adjusting Terminal settings"

## Enable focus follows mouse for Terminal and all X11 applications
defaults write com.apple.Terminal FocusFollowsMouse -bool true
defaults write org.x.X11 wm_ffm -bool true

## Use UTF-8 in Terminal
defaults write com.apple.Terminal StringEncodings -array 4

## Disable the audible bell in Terminal
$PLISTBUDDY \
  -c "Delete :WindowSettings:Basic:Bell" \
  -c "Add :WindowSettings:Basic:Bell bool false" \
  "${HOME}"/Library/Preferences/com.apple.Terminal.plist

## Enable the visual bell in Terminal
$PLISTBUDDY \
  -c "Delete :WindowSettings:Basic:VisualBell" \
  -c "Add :WindowSettings:Basic:VisualBell bool true" \
  "${HOME}"/Library/Preferences/com.apple.Terminal.plist

##== TextEdit =================================================================#

echo "Adjusting TextEdit settings"

## Do not automatically save ".txt" extensions on plain text files in TextEdit
defaults write com.apple.TextEdit AddExtensionToNewPlainTextFiles -bool false

## Disable automatic spelling correction (auto-correct) in TextEdit
defaults write com.apple.TextEdit CorrectSpellingAutomatically -bool false

## Set the TextEdit window height to thirty two characters
defaults write com.apple.TextEdit HeightInChars -int 32

## Display HTML files as HTML code, instead of formatted text in TextEdit
defaults write com.apple.TextEdit IgnoreHTML -bool true

## Set the TextEdit plain text font t Inconsolata
## NOTE: Install the Google Font "Inconsolata" before using this method
defaults write com.apple.TextEdit NSFixedPitchFont -string "Inconsolata-Regular"

## Set the TextEdit plain text font size to eighteen points
defaults write com.apple.TextEdit NSFixedPitchFontSize -string "18.0"

## Make TextEdit open files as UTF-8
defaults write com.apple.TextEdit PlainTextEncoding -int 4

## Make TextEdit save files as UTF-8
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

## Make TextEdit use plain text mode when new documents are created
defaults write com.apple.TextEdit RichText -bool false

## Make TextEdit wrap long lines
defaults write com.apple.TextEdit ShowPageBreaks -bool true

## Show the TextEdit ruler
defaults write com.apple.TextEdit ShowRuler -bool true

## Disable smart dashes TextEdit
defaults write com.apple.TextEdit SmartDashes -bool false

## Disable smart quotes TextEdit
defaults write com.apple.TextEdit SmartQuotes -bool false

## Set the TextEdit window width to eighty characters
defaults write com.apple.TextEdit WidthInChars -int 80

##== Time Machine =============================================================#

echo "Adjusting Time Machine settings"

## Disable Time Machine new hard drive as backup volume dialog box
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

## Disable local Time Machine snapshots/backups
hash tmutil &> /dev/null && sudo tmutil disablelocal

##== Trash ====================================================================#

echo "Adjusting Trash settings"

## Securely empty the Trash by default
defaults write com.apple.finder EmptyTrashSecurely -bool true

## Disable the "Are you sure..." warning dialog box when emptying the Trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

##== Users and Groups =========================================================#

echo "Adjusting Users and Groups settings"

## Show detailed system info when the login window clock is clicked
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

## Disable guest login on this computer
sudo defaults write /Library/Preferences/com.apple.loginwindow GuestEnabled -bool false

## Show power buttons at the login window
sudo defaults write /Library/Preferences/com.apple.loginwindow PowerOffDisabled -bool false

## Display full names of users at the login window
sudo defaults write /Library/Preferences/com.apple.loginwindow SHOWFULLNAME -bool true

## Disable automatic login
sudo defaults delete /Library/Preferences/com.apple.loginwindow autoLoginUser 2>/dev/null

## Show password hints Never
## (alternatives: enter an integer representing the number of guesses)
defaults write NSGlobalDomain RetriesUntilHint -int 0

## Show fast user switching menu as Account Name in the menu bar
## (alternatives: 0=Full Name|2=Icon)
defaults write NSGlobalDomain userMenuExtraStyle -int 1

##== Restart Affected Applications ============================================#

echo "Restarting affected applications"

## Reset Launchpad, without modifying the desktop background
find "${HOME}"/Library/Application\ Support/Dock -name "*-*.db" -maxdepth 1 -delete

## OS X applications to kill
os_x_apps_to_kill=(
  "Activity Monitor"
  "Address Book"
  "Calendar"
  "Contacts"
  "Disk Utility"
  "Dock"
  "Finder"
  "Font Book"
  "Mail"
  "Messages"
  "Photos"
  "Preview"
  "QuickTime Player"
  "Safari"
  "SystemUIServer"
  "TextEdit"
  "Xcode"
  "cfprefsd"
  "iCal"
)

## Kill OS X applications
appkillinator "${os_x_apps_to_kill[@]}"
