# .scss-lint.yml

####= SuitAndCape scss-lint Configurations
##============================================================================##

## Limit Hex restrictions and allow Harry Roberts' style BEM syntax

linters:
  HexLength:
    enabled: false

  HexNotation:
    enabled: false

  LeadingZero:
    enabled: true
    style: include_zero

  NameFormat:
    convention: '^([a-z][a-z]*(-{0,2}[a-z0-9]*)(_{0,2}[a-z0-9]*))*[^-_0-9]$'

  PlaceholderInExtend:
    enabled: false

  SelectorFormat:
    convention: hyphenated_BEM
