#!/bin/sh
# cli

####= SuitAndCape Command Line Interface Setup
##============================================================================##

if [[ "$OSTYPE" == "darwin"* ]]; then
  ## Install available system updates (`ia`) and output verbosely (`v`)
  sudo softwareupdate -iav

  ## Install Xcode, if it isn't installed already
  if ! $(xcode-select -p &>/dev/null); then
    xcode-select --install &>/dev/null

    ## Suspend execution for three seconds
    while ! xcode-select -p &> /dev/null; do
      sleep 3
    done
  fi

  ## Accept the Xcode license agreement
  if ! $(sudo xcodebuild -license status); then
    sudo xcodebuild -license accept
  fi
elif [[ "$OSTYPE" == "linux"* ]]; then
  echo "No Linux CLI setup available at this time."
fi
