#!/usr/bin/env bash
# code

####= SuitAndCape Code Setup
##============================================================================##

if [[ "$OSTYPE" == "darwin"* ]]; then

  ## Install Go via Homebrew
  brew install go

  ## Install jEnv via Homebrew
  brew install jenv

  ## Install Java 7 via Homebrew Cask
  brew cask install java7

  ## Install Java 8 via Homebrew Cask
  brew cask install java

  ## Install Python 2 via Homebrew
  brew install python

  if (which python > /dev/null); then
    ## Install PyQt via Homebrew
    brew install pyqt

    ## Update Pip and Setuptools
    pip install -U pip setuptools

    ## Install Virtualenv (Pip)
    pip install virtualenv
  fi

  ## Install Python 3 via Homebrew
  brew install python3

  if (which python3 > /dev/null); then
    ## Install Py3Cairo via Homebrew
    brew install py3cairo

    ## Update Pip3 and Setuptools
    pip3 install -U pip setuptools

    ## Install Virtualenv (Pip3)
    pip3 install virtualenv
  fi

  ## Install chruby via Homebrew
  brew install chruby

  ## Install ruby-install via Homebrew
  brew install ruby-install

  if (which ruby-install > /dev/null); then
    ## Install Ruby 2.0.0 via ruby-install
    ruby-install ruby 2.0.0

    ## Install Ruby 2.3.0 via ruby-install
    ruby-install ruby 2.3.0

    ## Update RubyGems and locally installed Gems
    gem update --system; gem update

    ## Install Bundler
    gem install bundler

    ## Remove outdated versions of Gems
    gem cleanup
  fi

elif [[ "$OSTYPE" == "linux"* ]]; then
  echo "No Linux Code setup available at this time."
fi
