#!/usr/bin/env bash
# package-managers

####= SuitAndCape Package Managers Setup
##============================================================================##

## Require the administrator password
sudo -v

## Keep updating `sudo` timestamp until `package-managers` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

if [[ "$OSTYPE" == "darwin"* ]]; then
  ## Create launchd service processes directory, if it doesn't exist
  if [[ ! -d "$HOME/Library/LaunchAgents" ]]; then
    mkdir -p "$HOME/Library/LaunchAgents"
  fi

  ## Set user permissions for the /use/local/ software directory
  sudo chown -R $USER /usr/local

  ## Set user permissions for launchd service processes directory
  sudo chown -R $USER $HOME/Library/LaunchAgents

  ## Install Homebrew, if it isn't installed already
  if ! (which brew > /dev/null); then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
  fi

  if (which brew > /dev/null); then
    ## Update all outdated locally installed Homebrew Formulae
    brew update && brew upgrade --all

    ## Update Cask
    brew cask update

    ## Locally install Homebrew Formulae
    brew tap homebrew/bundle
    brew bundle --file=configure/packages/Brewfile

    ## Remove outdated Formulae and Casks from the cellar and the caskroom
    brew cleanup; brew cask cleanup; brew prune

    ## Create a Zsh shell `[⇥]` autocompletion for `brew` symlink
    ln -s "$(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh" /usr/local/share/zsh/site-functions/_brew

    ## Create a Homebrew maintained GNU core utilities symlink
    ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

    ## Add Homebrew installed Bash 4 and Zsh 5 to the system shells list
    command -v bash | sudo tee -a /etc/shells
    command -v zsh | sudo tee -a /etc/shells
  fi

  if (which node > /dev/null); then
    ## Create a hidden $HOME/.npm-global directory
    mkdir -p "${HOME}/.npm-global"

    ## Create an NPM config file and store global packages in $HOME/.npm-global
    echo prefix=~/.npm-global >> ~/.npmrc

    ## Set user permissions for the $HOME/.npm-global directory
    sudo chown -R $USER:admin $HOME/.npm-global

    ## Install NPM
    curl -fsSL https://www.npmjs.com/install.sh | sudo sh

    ## Ensure NPM is properly installed (globally) and up-to-date
    npm install npm -g

    ## Install NPM Bash autocompletions
    npm completion > /usr/local/etc/bash_completion.d/npm

    ## NPM packages
    npm_packages=(
      grunt-cli
      gulp
      gulp-cli
      http-server
    )

    ## Globally install NPM packages
    npm install -g "${npm_packages[@]}"

    ## Remove data from the NPM cache folder
    npm cache clean
  fi
elif [[ "$OSTYPE" == "linux"* ]]; then
  echo "No Linux Package Managers setup available at this time."
fi
