#!/usr/bin/env bash
# settings

####= SuitAndCape Settings Setup
##============================================================================##

if [[ "$OSTYPE" == "darwin"* ]]; then
  ./configure/system/osx-settings
elif [[ "$OSTYPE" == "linux"* ]]; then
  ./configure/system/linux-settings
fi
