#!/usr/bin/env bash
# shells

####= SuitAndCape Shells Setup
##============================================================================##

## Menu-select style shell selector
echo -e "Select a default shell:"
echo -e "\tUse Bash as the default shell [B/b]"
echo -e "\tUse Zsh as the default shell [Z/z]"
while true; do
  read user_selection
  case $user_selection in
    B|b)
      ## Set shell to Bash
      bashinator ; echo "The default shell is now Bash" ; break ;;
    Z|z)
      ## Set shell to Zsh
      zshinator ; echo "The default shell is now Zsh" ; break ;;
    *)
      echo "Invalid option, please try again" ;;
  esac
done
